### ISSUE TITLE
Wrong URL in description

### ISSUE THREAD

**Issue by KristjanESPERANTO** [sdetweil/MMM-pages#5]
The website URL has a majuscle `P`, but it should be a minuscle `p`. It redirects to the correct one, but it is still incorrect. This cannot be fixed by a PR. Sorry for all the nitpicking 🫣

![Screenshot from 2024-06-24 22-42-24](https://github.com/sdetweil/MMM-pages/assets/35647502/f362e9e5-3944-4c49-b438-3fb2d7bc7dfd)

**Comment by sdetweil** [comment]
fixed a while back

**Comment by KristjanESPERANTO** [comment]
@sdetweil No, it's still wrong like in the screenshot :slightly_frowning_face:

**Comment by sdetweil** [comment]
![Screenshot at 2024-11-21 16-25-26](https://github.com/user-attachments/assets/eb569d36-4f63-4426-8da0-4b521354fdb2)

got it..

**Comment by KristjanESPERANTO** [comment]
Perfect! Thanks :slightly_smiling_face:
